# Generated by Django 4.1.13 on 2023-12-04 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProveeFruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=12)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('tipo_fruta', models.CharField(max_length=80)),
                ('origen', models.CharField(max_length=70)),
                ('tempo_cultivo', models.DateField()),
                ('precio', models.FloatField()),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('proveedorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.proveefruta')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('creacion', models.DateField()),
                ('actualizacion', models.DateField()),
                ('frutaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.fruta')),
            ],
        ),
    ]
